### ISSUE TITLE
Instructions unclear, can’t figure out how you got a ranger catppuccin theme…

### ISSUE THREAD

**Issue by thekeith** [command-z-z/dotfiles#1]
Love the setup but not sure how you got catppuccin in ranger. Any tips? I’m using zsh+tmux+starship+helix+ranger and have everything set except ranger to the right colors.

**Comment by command-z-z** [comment]
> 

In fact, you only need set colorscheme default in rc.conf in ranger's config. ranger will set its theme along with your terminal theme(btw, i use kitty with catpptccin theme). Thank you for your loving:)

**Comment by command-z-z** [comment]
complete
